import {
  DashboardOutlined,
  UserOutlined,
  UnorderedListOutlined,
  UserAddOutlined,
  SettingOutlined,
  ProfileOutlined,
  ToolOutlined,
  LaptopOutlined,
  InsertRowLeftOutlined,
  BankOutlined,
  TruckOutlined,
  DollarOutlined,
  FileTextOutlined,
  FrownOutlined,
  TransactionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  ReadOutlined,
  CommentOutlined,
  ThunderboltOutlined,
  TeamOutlined,
  ContainerOutlined,
  CoffeeOutlined,
  AppstoreOutlined,
  MenuOutlined,
} from "@ant-design/icons";
const icons: any = {
  DashboardOutlined: <DashboardOutlined />,
  UnorderedListOutlined: <UnorderedListOutlined />,
  UserAddOutlined: <UserAddOutlined />,
  SettingOutlined: <SettingOutlined />,
  LaptopOutlined: <LaptopOutlined />,
  ProfileOutlined: <ProfileOutlined />,
  InsertRowLeftOutlined: <InsertRowLeftOutlined />,
  BankOutlined: <BankOutlined />,
  ToolOutlined: <ToolOutlined />,
  TruckOutlined: <TruckOutlined />,
  DollarOutlined: <DollarOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FrownOutlined: <FrownOutlined />,
  TransactionOutlined: <TransactionOutlined />,
  FundProjectionScreenOutlined: <FundProjectionScreenOutlined />,
  FundViewOutlined: <FundViewOutlined />,
  ReadOutlined: <ReadOutlined />,
  CommentOutlined: <CommentOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  TeamOutlined: <TeamOutlined />,
  ContainerOutlined: <ContainerOutlined />,
  CoffeeOutlined: <CoffeeOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  UserOutlined: <UserOutlined />,
  MenuOutlined: <MenuOutlined />,
};

export default icons;
